<a href="https://colab.research.google.com/github/Kannow77/Bile-Initiative-AI-Track/blob/main/machine-learning/student_at_risk_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DAY ONE - AI FOUNDATIONS AND SETUP

## loading and reviewing data

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("student-por.csv",sep=";")

In [3]:
df.head()

  school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        4   0  11  11
1     GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2     GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3     GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4     GP   F   16       U     GT3       T  ...     2       5        0  11  13  13

[5 rows x 33 columns]

In [4]:
df.tail()

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
644     MS   F   19       R     GT3       T  ...     2       5        4  10  11  10
645     MS   F   18       U     LE3       T  ...     1       1        4  15  15  16
646     MS   F   18       U     GT3       T  ...     1       5        6  11  12   9
647     MS   M   17       U     LE3       T  ...     4       2        6  10  10  10
648     MS   M   18       R     LE3       T  ...     4       5        4  10  11  11

[5 rows x 33 columns]

In [5]:
df.shape

(649, 33)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

# Day 2 EDA

In [7]:
new_df = df.copy()

In [8]:
new_df.isnull().sum()

# isn()
new_df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [9]:
# drop()
new_df.drop(columns=["school"])
new_df


# drop index
new_df.drop(index=0)

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
1       GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2       GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3       GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4       GP   F   16       U     GT3       T  ...     2       5        0  11  13  13
5       GP   M   16       U     LE3       T  ...     2       5        6  12  12  13
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
644     MS   F   19       R     GT3       T  ...     2       5        4  10  11  10
645     MS   F   18       U     LE3       T  ...     1       1        4  15  15  16
646     MS   F   18       U     GT3       T  ...     1       5        6  11  12   9
647     MS   M   17       U     LE3       T  ...     4       2        6  10  10  10
648     MS   M   18       R     LE3       T  ...     4       5        4  10  11  11

[648 rows x 33 columns]

In [10]:
# dropna()
new_df.dropna()

# subset
new_df.dropna(subset=["school"])

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        4   0  11  11
1       GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2       GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3       GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4       GP   F   16       U     GT3       T  ...     2       5        0  11  13  13
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
644     MS   F   19       R     GT3       T  ...     2       5        4  10  11  10
645     MS   F   18       U     LE3       T  ...     1       1        4  15  15  16
646     MS   F   18       U     GT3       T  ...     1       5        6  11  12   9
647     MS   M   17       U     LE3       T  ...     4       2        6  10  10  10
648     MS   M   18       R     LE3       T  ...     4       5        4  10  11  11

[649 rows x 33 columns]

In [11]:
# filnna()
new_df["school"].mode()

0    GP
Name: school, dtype: object

In [12]:
new_df["school"]=new_df["school"].fillna(new_df["school"].mode()[0])

In [13]:
# numerical
new_df["age"].median()

17.0

In [14]:
new_df["age"].fillna(new_df["age"].median()).astype(int)

0      18
1      17
2      15
3      15
4      16
       ..
644    19
645    18
646    18
647    17
648    18
Name: age, Length: 649, dtype: int64

In [15]:
# dupliactes
# False, first,last
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

In [16]:
new_df=new_df.drop_duplicates()

In [17]:
new_df.head()

  school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        4   0  11  11
1     GP   F   17       U     GT3       T  ...     1       3        2   9  11  11
2     GP   F   15       U     LE3       T  ...     3       3        6  12  13  12
3     GP   F   15       U     GT3       T  ...     1       5        0  14  14  14
4     GP   F   16       U     GT3       T  ...     2       5        0  11  13  13

[5 rows x 33 columns]

In [18]:
new_df["at_risk"]=(new_df["G3"]<10).astype(int)

In [19]:
new_df.head()

  school sex  age address famsize  ... absences  G1  G2  G3 at_risk
0     GP   F   18       U     GT3  ...        4   0  11  11       0
1     GP   F   17       U     GT3  ...        2   9  11  11       0
2     GP   F   15       U     LE3  ...        6  12  13  12       0
3     GP   F   15       U     GT3  ...        0  14  14  14       0
4     GP   F   16       U     GT3  ...        0  11  13  13       0

[5 rows x 34 columns]

In [20]:
features = [
    "studytime", "failures", "schoolsup", "famsup", "activities",
    "higher", "internet", "famrel", "health", "absences"
]

X=new_df[features].copy()

In [21]:
X

     studytime  failures schoolsup famsup  ... internet famrel health  absences
0            2         0       yes     no  ...       no      4      3         4
1            2         0        no    yes  ...      yes      5      3         2
2            2         0       yes     no  ...      yes      4      3         6
3            3         0        no    yes  ...      yes      3      5         0
4            2         0        no    yes  ...       no      4      5         0
..         ...       ...       ...    ...  ...      ...    ...    ...       ...
644          3         1        no     no  ...      yes      5      5         4
645          2         0        no    yes  ...      yes      4      1         4
646          2         0        no     no  ...       no      1      5         6
647          1         0        no     no  ...      yes      2      2         6
648          1         0        no     no  ...      yes      4      5         4

[649 rows x 10 columns]

In [22]:
Y=new_df["at_risk"]

In [23]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: at_risk, Length: 649, dtype: int64

In [24]:
class_balance= Y.value_counts()

In [25]:
class_balance

at_risk
0    549
1    100
Name: count, dtype: int64

In [26]:
model_data=X.copy()

In [27]:
model_data["at_risk"]=Y

In [28]:
model_data.head()

   studytime  failures schoolsup famsup  ... famrel health absences  at_risk
0          2         0       yes     no  ...      4      3        4        0
1          2         0        no    yes  ...      5      3        2        0
2          2         0       yes     no  ...      4      3        6        0
3          3         0        no    yes  ...      3      5        0        0
4          2         0        no    yes  ...      4      5        0        0

[5 rows x 11 columns]

In [42]:
model_data.to_csv(
    "student-cleaned-data.csv",
    index=False
)

## Day 3: Model Training with Decision Tree

Now we will prepare the data for modeling, split it into training and testing sets, and train a Decision Tree classifier.

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score, classification_report

In [44]:
# Separate features (X) and target (y)
X = model_data.drop('at_risk', axis=1)
y = model_data['at_risk']

# Identify categorical and numerical features based on user input
numerical_features = [
    "studytime",
    "failures",
    "famrel",
    "health",
    "absences"
]

categorical_features = [
    "schoolsup",
    "famsup",
    "activities",
    "higher",
    "internet"
]

In [45]:
# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', StandardScaler(), numerical_features)
    ])

In [46]:
# Create a pipeline with preprocessing and Decision Tree classifier
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [47]:
print("Data split into training and testing sets.")
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")

Data split into training and testing sets.
Training features shape: (519, 10)
Testing features shape: (130, 10)
Training target shape: (519,)
Testing target shape: (130,)

### 3. Model Training

In [48]:
# Train the model
model_pipeline.fit(X_train, y_train)

print("Decision Tree model trained successfully.")

Decision Tree model trained successfully.

### 4. Test Prediction

In [49]:
# Make predictions on the test set
y_pred = model_pipeline.predict(X_test)

print("Predictions made on the test set.")

Predictions made on the test set.

### 5. Evaluate Model

In [50]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
f1= f1_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.4f}")
print(f"Model Recall: {recall:.4f}")
print(f"Model Precision: {precision:.4f}")
print(f"Model F1 Score: {f1:.4f}")
print("\nClassification Report:\n")
print(report)

Model Accuracy: 0.7692
Model Recall: 0.2000
Model Precision: 0.2222
Model F1 Score: 0.2105

Classification Report:

              precision    recall  f1-score   support

           0       0.86      0.87      0.86       110
           1       0.22      0.20      0.21        20

    accuracy                           0.77       130
   macro avg       0.54      0.54      0.54       130
weighted avg       0.76      0.77      0.76       130

In [51]:
import pandas as pd

metrics_data = {
    'Metric': ['Accuracy', 'Recall', 'Precision', 'F1 Score'],
    'Score': [accuracy, recall, precision, f1]
}
metrics_df = pd.DataFrame(metrics_data)
display(metrics_df)

      Metric     Score
0   Accuracy  0.769231
1     Recall  0.200000
2  Precision  0.222222
3   F1 Score  0.210526

In [51]:
#other model called logistic regration to make comparison

## Day 3: Model Training with Logistic Regression

Now we will train a Logistic Regression model and compare its performance with the Decision Tree.

In [52]:
from sklearn.linear_model import LogisticRegression

# Create a pipeline with preprocessing and Logistic Regression classifier
logistic_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42, solver='liblinear'))
])

# Train the Logistic Regression model
logistic_pipeline.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

### 4. Test Prediction (Logistic Regression)

In [53]:
# Make predictions on the test set using Logistic Regression
y_pred_lr = logistic_pipeline.predict(X_test)

print("Predictions made on the test set using Logistic Regression.")

Predictions made on the test set using Logistic Regression.

### 5. Evaluate Logistic Regression Model

In [54]:
# Evaluate the Logistic Regression model
accuracy_lr = accuracy_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
report_lr = classification_report(y_test, y_pred_lr)

print(f"Logistic Regression Model Accuracy: {accuracy_lr:.4f}")
print(f"Logistic Regression Model Recall: {recall_lr:.4f}")
print(f"Logistic Regression Model Precision: {precision_lr:.4f}")
print(f"Logistic Regression Model F1 Score: {f1_lr:.4f}")
print("\nLogistic Regression Classification Report:\n")
print(report_lr)

Logistic Regression Model Accuracy: 0.8385
Logistic Regression Model Recall: 0.1000
Logistic Regression Model Precision: 0.4000
Logistic Regression Model F1 Score: 0.1600

Logistic Regression Classification Report:

              precision    recall  f1-score   support

           0       0.86      0.97      0.91       110
           1       0.40      0.10      0.16        20

    accuracy                           0.84       130
   macro avg       0.63      0.54      0.54       130
weighted avg       0.79      0.84      0.80       130

In [55]:
import pandas as pd

# Compare the both model resullts
comparison_metrics_data = {
    'Metric': ['Accuracy', 'Recall', 'Precision', 'F1 Score'],
    'Decision Tree': [accuracy, recall, precision, f1],
    'Logistic Regression': [accuracy_lr, recall_lr, precision_lr, f1_lr]
}
comparison_df = pd.DataFrame(comparison_metrics_data)

display(comparison_df)

      Metric  Decision Tree  Logistic Regression
0   Accuracy       0.769231             0.838462
1     Recall       0.200000             0.100000
2  Precision       0.222222             0.400000
3   F1 Score       0.210526             0.160000

In [56]:
model_data.shape

(649, 11)